version: "3.3"
services:
    md_api:
        container_name: ${API_CONTAINER_NAME}
        build:
            context: api
            dockerfile: Dockerfile
        restart: always
        env_file:
            - ./.env
        volumes:
            - ${API_DIR}:/var/www/html/api
            - ./api/api.conf:/etc/apache2/sites-enabled/000-default.conf
            - ./api/hosts:/etc/hosts
        ports:
            - ${API_PORT}:80
        networks:
            md_dev_network:
                ipv4_address: ${API_IP}
        links:
            - ${MYSQL_CONTAINER_NAME}
            - ${REDIS_CONTAINER_NAME}
    md_phpmyadmin:
        container_name: ${PHPMYADMIN_CONTAINER_NAME}
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - ${PHPMYADMIN_PORT}:80
        environment:
            - PMA_ARBITRARY=1
        networks:
            md_dev_network:
                ipv4_address: ${PHPMYADMIN_IP}
        links:
            - ${MYSQL_CONTAINER_NAME}
    md_mysql:
        container_name: ${MYSQL_CONTAINER_NAME}
        image: 'mysql:5.7.31'
        env_file:
            - ./.env
        environment:
            MYSQL_ROOT_PASSWORD: '${MYSQL_USER}'
            MYSQL_USER: '${MYSQL_PASS}'
        command: mysqld --sql_mode=""
        restart: always
        volumes:
            - ${MYSQL_DIR}:/var/lib/mysql
        ports:
            - ${MYSQL_PORT}:${MYSQL_PORT}
        expose:
            - '${MYSQL_PORT}'
        networks:
            md_dev_network:
                ipv4_address: ${MYSQL_IP}
    md_redis:
        container_name: ${REDIS_CONTAINER_NAME}
        image: 'redis:latest'
        restart: always
        env_file:
            - ./.env
        volumes:
            - ${REDIS_DIR}:/data
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        expose:
            - '${REDIS_PORT}'
        networks:
            md_dev_network:
                ipv4_address: ${REDIS_IP}
networks:
    md_dev_network:
        ipam:
            config:
                - subnet: ${NETWORK_SUBNET}
volumes:
    persistent:
